"""Criar tabela de produtos e categorias

Revision ID: 4caeb87c82cd
Revises: b9ae3fe5ee12
Create Date: 2026-06-10 15:09:56.872280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4caeb87c82cd'
down_revision: Union[str, Sequence[str], None] = 'b9ae3fe5ee12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
